name: Branch Protection

on:
  pull_request:

jobs:
  setup:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Setup yarn
        run: |
          npm install -g yarn
          yarn
      - name: Create .env
        run: |
          touch .env.local
          echo NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }} >> .env
          echo NEXT_PUBLIC_FIREBASE_API_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_API_ID }} >> .env
          echo NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }} >> .env
          echo NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }} >> .env
          echo NEXT_PUBLIC_LOG_LEVEL=debug >> .env
        #  cat .env
      - name: Build submodules
        run: yarn build:dependencies
      - name: Lint
        run: yarn lint
      - name: Type Check
        run: yarn typecheck
      - name: Unit Test
        run: yarn test
